"""v0.6 SDK.a — pack scaffold generator.

Pure-function templates + writer. Generates the 4 canonical files
a new ontology pack starts with:

  * ``pack.py``   — minimal :class:`OntologyPack` stub
  * ``test_pack.py`` — mount + 4-vertical-test scaffold
  * ``LICENSE``  — MIT default (operator can replace)
  * ``README.md`` — quickstart pointing at the author guide

Operator can override the template content via custom templates
in a later iteration; for now the defaults are mother-platform
canonical.
"""
from __future__ import annotations

import os
import re
from typing import Dict, List


# Pack-id sanity: lowercase identifiers + dashes + version suffix.
# Examples: `legal-demo-v1`, `finance-baseline-v2`. Reject names
# that contain path separators / spaces / shell metachars.
_PACK_ID_RE = re.compile(r"^[a-z][a-z0-9_]*(-[a-z0-9_]+)*$")


def validate_pack_id(pack_id: str) -> None:
    """Raise ValueError if `pack_id` is not a valid identifier.

    Rules:
      * Must start with a lowercase letter.
      * Body of lowercase letters, digits, underscores,
        optionally separated by single dashes.
      * No path separators / spaces / shell metachars.

    Reject is strict by design — pack ids surface in audit log
    payloads + file paths; loose validation invites injection.
    """
    if not isinstance(pack_id, str):
        raise ValueError(
            f"pack_id must be a string, got {type(pack_id).__name__}"
        )
    if not pack_id:
        raise ValueError("pack_id must be non-empty")
    if not _PACK_ID_RE.match(pack_id):
        raise ValueError(
            f"pack_id {pack_id!r} not allowed; must match "
            f"r'{_PACK_ID_RE.pattern}' (lowercase letters/digits/"
            f"underscores/dashes, must start with a letter)"
        )


def _module_safe_name(pack_id: str) -> str:
    """Convert pack_id to a Python module-safe name.

    Pack ids allow dashes; module names cannot. Replace `-` → `_`.
    """
    return pack_id.replace("-", "_")


def render_pack_py(pack_id: str) -> str:
    """Render the minimal `pack.py` template."""
    var_name = _module_safe_name(pack_id).upper() + "_PACK"
    return (
        '"""Ontology pack: ' + pack_id + '.\n\n'
        'Generated by `python -m james.pack init ' + pack_id + '`.\n'
        'See `docs/ONTOLOGY_PACK_AUTHORING.md` for the author guide.\n'
        '"""\n'
        'from core.ontology_packs import OntologyPack\n\n\n'
        + var_name + ' = OntologyPack(\n'
        '    pack_id="' + pack_id + '",\n'
        '    # Capability the operator must grant via JAMES_CAPABILITIES.\n'
        '    # If this pack contains vertical content (per the 4-vertical\n'
        '    # test in the author guide §5), use:\n'
        '    #   requires_capability="rule_one_exemption_granted"\n'
        '    # which is gated on signed customer LOI + v0.6 / v1.0 scope.\n'
        '    requires_capability="rule_one_exemption_granted",\n'
        '    subtypes={\n'
        '        # "your_subtype": {\n'
        '        #     "parent": "document",   # mother entity type\n'
        '        #     "since":  "v0.6",\n'
        '        # },\n'
        '    },\n'
        '    relation_types={\n'
        '        # "YOUR_RELATION": {\n'
        '        #     "label":     "your-label",\n'
        '        #     "inverse":   "INVERSE_RELATION",\n'
        '        #     "transitive": False,\n'
        '        #     "weight":     1.0,\n'
        '        #     "sensitive":  False,\n'
        '        #     "allowed_head": {"document"},\n'
        '        #     "allowed_tail": {"document"},\n'
        '        # },\n'
        '    },\n'
        '    enterprise_roles={\n'
        '        # "YOUR_ROLE": {\n'
        '        #     "perms_over_doc": {"read"},\n'
        '        # },\n'
        '    },\n'
        '    label_to_type={\n'
        '        # "label": "TYPE_NAME",\n'
        '    },\n'
        '    since="v0.6",\n'
        '    provenance="Add a one-line provenance: license, '
        'customer ref, signing date.",\n'
        ')\n'
    )


def render_test_pack_py(pack_id: str) -> str:
    """Render the minimal `test_pack.py` template."""
    var_name = _module_safe_name(pack_id).upper() + "_PACK"
    return (
        '"""Smoke tests for the ' + pack_id + ' pack.\n\n'
        'Run with: pytest test_pack.py\n'
        '"""\n'
        'import os\n'
        'import unittest\n'
        'from contextlib import contextmanager\n'
        'from typing import Dict\n\n'
        'from pack import ' + var_name + '\n\n\n'
        '@contextmanager\n'
        'def _patched_env(**env: str):\n'
        '    saved: Dict[str, str] = {}\n'
        '    unset_keys = []\n'
        '    for k, v in env.items():\n'
        '        if k in os.environ:\n'
        '            saved[k] = os.environ[k]\n'
        '        else:\n'
        '            unset_keys.append(k)\n'
        '        if v is None:\n'
        '            os.environ.pop(k, None)\n'
        '        else:\n'
        '            os.environ[k] = v\n'
        '    try:\n'
        '        yield\n'
        '    finally:\n'
        '        for k, v in saved.items():\n'
        '            os.environ[k] = v\n'
        '        for k in unset_keys:\n'
        '            os.environ.pop(k, None)\n\n\n'
        'class PackContractTests(unittest.TestCase):\n'
        '    def test_pack_has_valid_dataclass(self):\n'
        '        self.assertEqual(' + var_name + '.pack_id, "' + pack_id + '")\n'
        '        self.assertTrue(' + var_name + '.requires_capability)\n\n'
        '    def test_pack_cannot_mount_without_capability(self):\n'
        '        from core.ontology_packs import (\n'
        '            CapabilityNotGrantedError,\n'
        '            _reset_for_tests,\n'
        '            register_pack,\n'
        '        )\n'
        '        _reset_for_tests()\n'
        '        # Without JAMES_CAPABILITIES set, the capability gate fires.\n'
        '        with _patched_env(JAMES_CAPABILITIES=None):\n'
        '            with self.assertRaises(CapabilityNotGrantedError):\n'
        '                register_pack(' + var_name + ')\n\n'
        '    def test_pack_mounts_with_capability_granted(self):\n'
        '        from core.ontology_packs import (\n'
        '            _reset_for_tests,\n'
        '            mounted_packs,\n'
        '            register_pack,\n'
        '        )\n'
        '        _reset_for_tests()\n'
        '        with _patched_env(\n'
        '            JAMES_CAPABILITIES=' + var_name + '.requires_capability,\n'
        '        ):\n'
        '            register_pack(' + var_name + ')\n'
        '            self.assertEqual(len(mounted_packs()), 1)\n\n\n'
        'if __name__ == "__main__":\n'
        '    unittest.main()\n'
    )


def render_license() -> str:
    """Render a minimal MIT LICENSE template."""
    return (
        "MIT License\n\n"
        "Copyright (c) <year> <author>\n\n"
        "Permission is hereby granted, free of charge, to any person "
        "obtaining a copy of this software and associated documentation "
        "files (the \"Software\"), to deal in the Software without "
        "restriction, including without limitation the rights to use, "
        "copy, modify, merge, publish, distribute, sublicense, and/or "
        "sell copies of the Software, and to permit persons to whom the "
        "Software is furnished to do so, subject to the following "
        "conditions:\n\n"
        "The above copyright notice and this permission notice shall be "
        "included in all copies or substantial portions of the Software.\n\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, "
        "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES "
        "OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND "
        "NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT "
        "HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, "
        "WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING "
        "FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR "
        "OTHER DEALINGS IN THE SOFTWARE.\n"
    )


def render_readme(pack_id: str) -> str:
    """Render the README.md template."""
    return (
        "# " + pack_id + "\n\n"
        "Ontology pack for JAMES (`core/ontology_packs.py` mount "
        "mechanism).\n\n"
        "Scaffolded by `python -m james.pack init " + pack_id + "`.\n"
        "See `docs/ONTOLOGY_PACK_AUTHORING.md` (in the JAMES repo) "
        "for the author guide.\n\n"
        "## Quickstart\n\n"
        "```bash\n"
        "# 1. Edit pack.py — add your subtypes / relations / roles.\n"
        "# 2. Run the smoke test:\n"
        "pytest test_pack.py\n\n"
        "# 3. In your JAMES deployment, grant the capability\n"
        "#    (or use the default rule_one_exemption_granted) and mount:\n"
        "export JAMES_CAPABILITIES=\"rule_one_exemption_granted\"\n"
        "python -c \"from pack import "
        + _module_safe_name(pack_id).upper() + "_PACK; "
        "from core.ontology_packs import register_pack; "
        "register_pack(" + _module_safe_name(pack_id).upper()
        + "_PACK); print('mounted')\"\n"
        "```\n\n"
        "## License\n\n"
        "MIT — see `LICENSE`.\n"
    )


def scaffold_files(pack_id: str) -> Dict[str, str]:
    """Render all 4 canonical files as a name → content dict.

    Pure function; no I/O. The caller (CLI) writes them.
    """
    validate_pack_id(pack_id)
    return {
        "pack.py":      render_pack_py(pack_id),
        "test_pack.py": render_test_pack_py(pack_id),
        "LICENSE":      render_license(),
        "README.md":    render_readme(pack_id),
    }


def write_scaffold(pack_id: str, output_dir: str,
                   *, overwrite: bool = False) -> List[str]:
    """Write the scaffold to ``<output_dir>/<pack_id>/``.

    Args:
        pack_id: pack identifier (validated).
        output_dir: parent directory; the pack subdir is created
            under it.
        overwrite: when False (default), refuses to overwrite an
            existing directory; raises ``FileExistsError``. When
            True, writes over existing files (use sparingly).

    Returns:
        Sorted list of relative file paths written.
    """
    validate_pack_id(pack_id)
    pack_dir = os.path.join(output_dir, pack_id)
    if os.path.exists(pack_dir) and not overwrite:
        raise FileExistsError(
            f"refusing to write to existing directory "
            f"{pack_dir!r}; pass --overwrite to force"
        )
    os.makedirs(pack_dir, exist_ok=True)
    written: List[str] = []
    for fname, content in scaffold_files(pack_id).items():
        path = os.path.join(pack_dir, fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(os.path.join(pack_id, fname))
    written.sort()
    return written


__all__ = (
    "validate_pack_id",
    "scaffold_files",
    "render_pack_py",
    "render_test_pack_py",
    "render_license",
    "render_readme",
    "write_scaffold",
)
